# THIS FILE IS AUTO-GENERATED BY configure.py, DO NOT EDIT!

.PHONY: all clean

all: cppreflect/libcppreflect.a example/base/a.out example/enum/a.out example/fields/a.out example/luacall/a.out example/rpc/a.out
	@echo "[1;32mBuild success ...[0m"

# === build cxx target: cppreflect/libcppreflect.a ===
# ====== cppreflect/class_mgr.cpp =====
cppreflect/class_mgr.d: cppreflect/class_mgr.cpp
	g++ -E -MM -MG -MT 'cppreflect/class_mgr.o' -MF cppreflect/class_mgr.d -c cppreflect/class_mgr.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include cppreflect/class_mgr.d

cppreflect/class_mgr.o: cppreflect/class_mgr.cpp
	g++ -o cppreflect/class_mgr.o -c cppreflect/class_mgr.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== cppreflect/cppreflect_define.cpp =====
cppreflect/cppreflect_define.d: cppreflect/cppreflect_define.cpp
	g++ -E -MM -MG -MT 'cppreflect/cppreflect_define.o' -MF cppreflect/cppreflect_define.d -c cppreflect/cppreflect_define.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include cppreflect/cppreflect_define.d

cppreflect/cppreflect_define.o: cppreflect/cppreflect_define.cpp
	g++ -o cppreflect/cppreflect_define.o -c cppreflect/cppreflect_define.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== cppreflect/cppreflect_fundamental.cpp =====
cppreflect/cppreflect_fundamental.d: cppreflect/cppreflect_fundamental.cpp
	g++ -E -MM -MG -MT 'cppreflect/cppreflect_fundamental.o' -MF cppreflect/cppreflect_fundamental.d -c cppreflect/cppreflect_fundamental.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include cppreflect/cppreflect_fundamental.d

cppreflect/cppreflect_fundamental.o: cppreflect/cppreflect_fundamental.cpp
	g++ -o cppreflect/cppreflect_fundamental.o -c cppreflect/cppreflect_fundamental.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== cppreflect/cppreflect_string.cpp =====
cppreflect/cppreflect_string.d: cppreflect/cppreflect_string.cpp
	g++ -E -MM -MG -MT 'cppreflect/cppreflect_string.o' -MF cppreflect/cppreflect_string.d -c cppreflect/cppreflect_string.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include cppreflect/cppreflect_string.d

cppreflect/cppreflect_string.o: cppreflect/cppreflect_string.cpp
	g++ -o cppreflect/cppreflect_string.o -c cppreflect/cppreflect_string.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== cppreflect/eventcall_mgr.cpp =====
cppreflect/eventcall_mgr.d: cppreflect/eventcall_mgr.cpp
	g++ -E -MM -MG -MT 'cppreflect/eventcall_mgr.o' -MF cppreflect/eventcall_mgr.d -c cppreflect/eventcall_mgr.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include cppreflect/eventcall_mgr.d

cppreflect/eventcall_mgr.o: cppreflect/eventcall_mgr.cpp
	g++ -o cppreflect/eventcall_mgr.o -c cppreflect/eventcall_mgr.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== cppreflect/lua_mgr.cpp =====
cppreflect/lua_mgr.d: cppreflect/lua_mgr.cpp
	g++ -E -MM -MG -MT 'cppreflect/lua_mgr.o' -MF cppreflect/lua_mgr.d -c cppreflect/lua_mgr.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include cppreflect/lua_mgr.d

cppreflect/lua_mgr.o: cppreflect/lua_mgr.cpp
	g++ -o cppreflect/lua_mgr.o -c cppreflect/lua_mgr.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== cppreflect/rpc_mgr.cpp =====
cppreflect/rpc_mgr.d: cppreflect/rpc_mgr.cpp
	g++ -E -MM -MG -MT 'cppreflect/rpc_mgr.o' -MF cppreflect/rpc_mgr.d -c cppreflect/rpc_mgr.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include cppreflect/rpc_mgr.d

cppreflect/rpc_mgr.o: cppreflect/rpc_mgr.cpp
	g++ -o cppreflect/rpc_mgr.o -c cppreflect/rpc_mgr.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

cppreflect/libcppreflect.a: cppreflect/class_mgr.o cppreflect/cppreflect_define.o cppreflect/cppreflect_fundamental.o cppreflect/cppreflect_string.o cppreflect/eventcall_mgr.o cppreflect/lua_mgr.o cppreflect/rpc_mgr.o 
	ar -r cppreflect/libcppreflect.a cppreflect/class_mgr.o cppreflect/cppreflect_define.o cppreflect/cppreflect_fundamental.o cppreflect/cppreflect_string.o cppreflect/eventcall_mgr.o cppreflect/lua_mgr.o cppreflect/rpc_mgr.o


# === build cxx target: example/base/a.out ===
# ====== example/base/main.cpp =====
example/base/main.d: example/base/main.cpp
	g++ -E -MM -MG -MT 'example/base/main.o' -MF example/base/main.d -c example/base/main.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include example/base/main.d

example/base/main.o: example/base/main.cpp
	g++ -o example/base/main.o -c example/base/main.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== example/base/service_demo.cpp =====
example/base/service_demo.d: example/base/service_demo.cpp
	g++ -E -MM -MG -MT 'example/base/service_demo.o' -MF example/base/service_demo.d -c example/base/service_demo.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include example/base/service_demo.d

example/base/service_demo.o: example/base/service_demo.cpp
	g++ -o example/base/service_demo.o -c example/base/service_demo.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== example/base/vector3d.cpp =====
example/base/vector3d.d: example/base/vector3d.cpp
	g++ -E -MM -MG -MT 'example/base/vector3d.o' -MF example/base/vector3d.d -c example/base/vector3d.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include example/base/vector3d.d

example/base/vector3d.o: example/base/vector3d.cpp
	g++ -o example/base/vector3d.o -c example/base/vector3d.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== example/base/service_demo.generated.h =====
example/base/service_demo.generated.h: thirdparty/llvm/bin/clang-reflect example/base/service_demo.h
	thirdparty/llvm/bin/clang-reflect  example/base/service_demo.h -p=. > example/base/service_demo.generated.h

# ====== example/base/vector3d.generated.h =====
example/base/vector3d.generated.h: thirdparty/llvm/bin/clang-reflect example/base/vector3d.h
	thirdparty/llvm/bin/clang-reflect  example/base/vector3d.h -p=. > example/base/vector3d.generated.h

example/base/a.out: example/base/main.o example/base/service_demo.o example/base/vector3d.o cppreflect/libcppreflect.a
	g++ -o example/base/a.out example/base/main.o example/base/service_demo.o example/base/vector3d.o cppreflect/libcppreflect.a thirdparty/msgpack-c/libmsgpackc.a thirdparty/lua-5.3.5/liblua.a -rdynamic -fprofile-arcs


# === build cxx target: example/enum/a.out ===
# ====== example/enum/enum.cpp =====
example/enum/enum.d: example/enum/enum.cpp
	g++ -E -MM -MG -MT 'example/enum/enum.o' -MF example/enum/enum.d -c example/enum/enum.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include example/enum/enum.d

example/enum/enum.o: example/enum/enum.cpp
	g++ -o example/enum/enum.o -c example/enum/enum.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== example/enum/main.cpp =====
example/enum/main.d: example/enum/main.cpp
	g++ -E -MM -MG -MT 'example/enum/main.o' -MF example/enum/main.d -c example/enum/main.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include example/enum/main.d

example/enum/main.o: example/enum/main.cpp
	g++ -o example/enum/main.o -c example/enum/main.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== example/enum/enum.generated.h =====
example/enum/enum.generated.h: thirdparty/llvm/bin/clang-reflect example/enum/enum.h
	thirdparty/llvm/bin/clang-reflect  example/enum/enum.h -p=. > example/enum/enum.generated.h

example/enum/a.out: example/enum/enum.o example/enum/main.o cppreflect/libcppreflect.a
	g++ -o example/enum/a.out example/enum/enum.o example/enum/main.o cppreflect/libcppreflect.a thirdparty/msgpack-c/libmsgpackc.a thirdparty/lua-5.3.5/liblua.a -ldl -rdynamic -fprofile-arcs


# === build cxx target: example/fields/a.out ===
# ====== example/fields/main.cpp =====
example/fields/main.d: example/fields/main.cpp
	g++ -E -MM -MG -MT 'example/fields/main.o' -MF example/fields/main.d -c example/fields/main.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include example/fields/main.d

example/fields/main.o: example/fields/main.cpp
	g++ -o example/fields/main.o -c example/fields/main.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== example/fields/my_struct.cpp =====
example/fields/my_struct.d: example/fields/my_struct.cpp
	g++ -E -MM -MG -MT 'example/fields/my_struct.o' -MF example/fields/my_struct.d -c example/fields/my_struct.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include example/fields/my_struct.d

example/fields/my_struct.o: example/fields/my_struct.cpp
	g++ -o example/fields/my_struct.o -c example/fields/my_struct.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== example/fields/my_struct.generated.h =====
example/fields/my_struct.generated.h: thirdparty/llvm/bin/clang-reflect example/fields/my_struct.h
	thirdparty/llvm/bin/clang-reflect  example/fields/my_struct.h -p=. > example/fields/my_struct.generated.h

example/fields/a.out: example/fields/main.o example/fields/my_struct.o cppreflect/libcppreflect.a
	g++ -o example/fields/a.out example/fields/main.o example/fields/my_struct.o cppreflect/libcppreflect.a thirdparty/msgpack-c/libmsgpackc.a thirdparty/lua-5.3.5/liblua.a -rdynamic -fprofile-arcs


# === build cxx target: example/luacall/a.out ===
# ====== example/luacall/main.cpp =====
example/luacall/main.d: example/luacall/main.cpp
	g++ -E -MM -MG -MT 'example/luacall/main.o' -MF example/luacall/main.d -c example/luacall/main.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include example/luacall/main.d

example/luacall/main.o: example/luacall/main.cpp
	g++ -o example/luacall/main.o -c example/luacall/main.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== example/luacall/service_demo.cpp =====
example/luacall/service_demo.d: example/luacall/service_demo.cpp
	g++ -E -MM -MG -MT 'example/luacall/service_demo.o' -MF example/luacall/service_demo.d -c example/luacall/service_demo.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include example/luacall/service_demo.d

example/luacall/service_demo.o: example/luacall/service_demo.cpp
	g++ -o example/luacall/service_demo.o -c example/luacall/service_demo.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== example/luacall/vector3d.cpp =====
example/luacall/vector3d.d: example/luacall/vector3d.cpp
	g++ -E -MM -MG -MT 'example/luacall/vector3d.o' -MF example/luacall/vector3d.d -c example/luacall/vector3d.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include example/luacall/vector3d.d

example/luacall/vector3d.o: example/luacall/vector3d.cpp
	g++ -o example/luacall/vector3d.o -c example/luacall/vector3d.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== example/luacall/service_demo.generated.h =====
example/luacall/service_demo.generated.h: thirdparty/llvm/bin/clang-reflect example/luacall/service_demo.h
	thirdparty/llvm/bin/clang-reflect  example/luacall/service_demo.h -p=. > example/luacall/service_demo.generated.h

# ====== example/luacall/vector3d.generated.h =====
example/luacall/vector3d.generated.h: thirdparty/llvm/bin/clang-reflect example/luacall/vector3d.h
	thirdparty/llvm/bin/clang-reflect  example/luacall/vector3d.h -p=. > example/luacall/vector3d.generated.h

example/luacall/a.out: example/luacall/main.o example/luacall/service_demo.o example/luacall/vector3d.o cppreflect/libcppreflect.a
	g++ -o example/luacall/a.out example/luacall/main.o example/luacall/service_demo.o example/luacall/vector3d.o cppreflect/libcppreflect.a thirdparty/msgpack-c/libmsgpackc.a thirdparty/lua-5.3.5/liblua.a -ldl -rdynamic -fprofile-arcs


# === build cxx target: example/rpc/a.out ===
# ====== example/rpc/main.cpp =====
example/rpc/main.d: example/rpc/main.cpp
	g++ -E -MM -MG -MT 'example/rpc/main.o' -MF example/rpc/main.d -c example/rpc/main.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include example/rpc/main.d

example/rpc/main.o: example/rpc/main.cpp
	g++ -o example/rpc/main.o -c example/rpc/main.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== example/rpc/test.cpp =====
example/rpc/test.d: example/rpc/test.cpp
	g++ -E -MM -MG -MT 'example/rpc/test.o' -MF example/rpc/test.d -c example/rpc/test.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

include example/rpc/test.d

example/rpc/test.o: example/rpc/test.cpp
	g++ -o example/rpc/test.o -c example/rpc/test.cpp -std=c++11 -g -m64 -fPIC -pipe -fwrapv -fno-strict-aliasing -Wstrict-aliasing=2 -DMSGPACK_ENDIAN_LITTLE_BYTE -D_DEV_DEBUG -I. -Ithirdparty/lua-5.3.5/include -Ithirdparty/msgpack-c/include

# ====== example/rpc/test.generated.h =====
example/rpc/test.generated.h: thirdparty/llvm/bin/clang-reflect example/rpc/test.h
	thirdparty/llvm/bin/clang-reflect  example/rpc/test.h -p=. > example/rpc/test.generated.h

example/rpc/a.out: example/rpc/main.o example/rpc/test.o cppreflect/libcppreflect.a
	g++ -o example/rpc/a.out example/rpc/main.o example/rpc/test.o cppreflect/libcppreflect.a thirdparty/msgpack-c/libmsgpackc.a thirdparty/lua-5.3.5/liblua.a -rdynamic -fprofile-arcs



clean:
# clean target: cppreflect/libcppreflect.a
	rm -rf cppreflect/libcppreflect.a
	rm -rf cppreflect/class_mgr.o cppreflect/cppreflect_define.o cppreflect/cppreflect_fundamental.o cppreflect/cppreflect_string.o cppreflect/eventcall_mgr.o cppreflect/lua_mgr.o cppreflect/rpc_mgr.o
	rm -rf cppreflect/class_mgr.d cppreflect/cppreflect_define.d cppreflect/cppreflect_fundamental.d cppreflect/cppreflect_string.d cppreflect/eventcall_mgr.d cppreflect/lua_mgr.d cppreflect/rpc_mgr.d
	rm -rf cppreflect/class_mgr.gcno cppreflect/cppreflect_define.gcno cppreflect/cppreflect_fundamental.gcno cppreflect/cppreflect_string.gcno cppreflect/eventcall_mgr.gcno cppreflect/lua_mgr.gcno cppreflect/rpc_mgr.gcno
	rm -rf cppreflect/class_mgr.gcda cppreflect/cppreflect_define.gcda cppreflect/cppreflect_fundamental.gcda cppreflect/cppreflect_string.gcda cppreflect/eventcall_mgr.gcda cppreflect/lua_mgr.gcda cppreflect/rpc_mgr.gcda

# clean target: example/base/a.out
	rm -rf example/base/a.out
	rm -rf example/base/main.o example/base/service_demo.o example/base/vector3d.o
	rm -rf example/base/main.d example/base/service_demo.d example/base/vector3d.d
	rm -rf example/base/main.gcno example/base/service_demo.gcno example/base/vector3d.gcno
	rm -rf example/base/main.gcda example/base/service_demo.gcda example/base/vector3d.gcda
	rm -rf example/base/service_demo.generated.h example/base/vector3d.generated.h

# clean target: example/enum/a.out
	rm -rf example/enum/a.out
	rm -rf example/enum/enum.o example/enum/main.o
	rm -rf example/enum/enum.d example/enum/main.d
	rm -rf example/enum/enum.gcno example/enum/main.gcno
	rm -rf example/enum/enum.gcda example/enum/main.gcda
	rm -rf example/enum/enum.generated.h

# clean target: example/fields/a.out
	rm -rf example/fields/a.out
	rm -rf example/fields/main.o example/fields/my_struct.o
	rm -rf example/fields/main.d example/fields/my_struct.d
	rm -rf example/fields/main.gcno example/fields/my_struct.gcno
	rm -rf example/fields/main.gcda example/fields/my_struct.gcda
	rm -rf example/fields/my_struct.generated.h

# clean target: example/luacall/a.out
	rm -rf example/luacall/a.out
	rm -rf example/luacall/main.o example/luacall/service_demo.o example/luacall/vector3d.o
	rm -rf example/luacall/main.d example/luacall/service_demo.d example/luacall/vector3d.d
	rm -rf example/luacall/main.gcno example/luacall/service_demo.gcno example/luacall/vector3d.gcno
	rm -rf example/luacall/main.gcda example/luacall/service_demo.gcda example/luacall/vector3d.gcda
	rm -rf example/luacall/service_demo.generated.h example/luacall/vector3d.generated.h

# clean target: example/rpc/a.out
	rm -rf example/rpc/a.out
	rm -rf example/rpc/main.o example/rpc/test.o
	rm -rf example/rpc/main.d example/rpc/test.d
	rm -rf example/rpc/main.gcno example/rpc/test.gcno
	rm -rf example/rpc/main.gcda example/rpc/test.gcda
	rm -rf example/rpc/test.generated.h

